version: "3.9"

services:
  web:
    image: safedrop-prod-front:latest
    container_name: safedrop-prod-front
    build:
      context: .
      dockerfile: Dockerfile.prod
      platforms:
        - linux/amd64 # ensures it matches your VPS host platform
    ports:
      - "3000:80" # maps host port 3000 → container port 80
    environment:
      NODE_ENV: production
      # NEXT_PUBLIC_API_URL=http://backend:8000 (set if backend is on a different container)
    restart: unless-stopped
