version: "3.9"

services:
  web:
    image: safedrop-prod-front:latest
    container_name: safedrop-prod-front
    build:
      context: .
      dockerfile: Dockerfile.prod
      platforms: # Add this line/block
        - linux/amd64 # Targets AMD64 only; add more like - linux/arm64 for multi-arch
    ports:
      - "3000:3000" # Frontend + API proxy port
    environment:
      NODE_ENV: production
      # Add any other env vars here, e.g. NEXT_PUBLIC_API_URL, SECRET_KEY, etc.
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
